### PR TITLE
Add support for checking access against a repository

### PR DESCRIPTION
**Pull request by odormond**
I'm adding a `--bitbucket-repository` (and corresponding config option) to enable restricted access to users with write access to a given repo.

I also changed the default scope to the minimum required and added code to alter it to add scopes required for the options activated.

I just fixed the unit tests for the scope changes I introduced. I got ready for adding tests for the repository access control (by adding another argument to `testBitbucketProvider` but didn't actually added any test there because there is actually no test for the team filtering and my go experience isn't enough to do much more then copy-pasta-programming.

### CODE REVIEW

**Comment by odormond** [comment]
Is it possible that travis is having issue with the fact it's a fork? It build fine on my machine with go 1.10.

**Comment by aledeganopix4d** [comment]
I'm afraid that travis is broken (it was on the main repo too).
We should fix it...

**Comment by marco-m** [comment]
The current Travis configuration for this project builds with go 1.8 and 1.9 only.

**Comment by marco-m** [comment]
@odormond could you please have a look with @aledeganopix4d to fix travis (and getting rid of go versions before 1.10) ? Either here or in a separate PR.

**Comment by odormond** [comment]
I know nothing about travis but looking at the log I don't think he is to blame. I really think the problem comes from go's import/dependency system. If you look at the logs first of all you can notice that travis clones this repo... as expected, but that's precisely what you're not supposed to do in go and the side effect is reflected later in the log where you can see (stripped useless info):
```
$ go get -t -v ./...
github.com/bitly/oauth2_proxy (download)  <- BOOM
github.com/bitly/oauth2_proxy/cookie
github.com/bitly/oauth2_proxy/api
github.com/Pix4D/oauth2_proxy/api
github.com/Pix4D/oauth2_proxy/cookie
github.com/bitly/oauth2_proxy/providers
github.com/Pix4D/oauth2_proxy/providers
github.com/Pix4D/oauth2_proxy
```
So we get both the original fork source and this branch code. And the build fails with:
```
./options.go:266: undefined: providers.BitbucketProvider
```
Which makes perfect sense as the imports in this file look for:
```
package main

import (
        [SNIP standard lib imports]

        "github.com/bitly/oauth2_proxy/providers"  <- BOOM
        oidc "github.com/coreos/go-oidc"
        "github.com/mbland/hmacauth"
)
```

So, I see only two ways to fix it:
1. throw away go's import crap and replace any occurrence of `bitly` in the sources with `Pix4D`
2. throw away travis' clone and redo it from scratch

**Comment by kmdouglass** [comment]
One idea is to `rsync` your changes into the upstream repo on your Go path. You still duplicate the code in Travis, but your forked will be included in the build: http://www.ruflin.com/2015/08/13/fix-for-travis-ci-failure-in-forked-golang-repositories/
